version: '3.7'

services:
  #----------------------------------------------#
  # Pi-hole : dns wide blocking ads
  #----------------------------------------------#
  pihole:
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
    volumes:
      - pihole_data:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    networks:
      - traefik
    dns:
      - 127.0.0.1
      - 9.9.9.9
    environment:
      - VIRTUAL_HOST=pihole.${DOMAINNAME}
      - VIRTUAL_PORT=80
      - TZ=${TZ}
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole.rule=Host(`pihole.${DOMAINNAME}`)
      - traefik.http.routers.pihole.entrypoints=https
      - traefik.http.routers.pihole.tls.domains[0].main=${DOMAINNAME}
      - traefik.http.routers.pihole.tls.domains[0].sans=*.${DOMAINNAME}
      - traefik.http.routers.pihole.tls.certresolver=ovh
      # - traefik.http.routers.pihole.middlewares=default-auth@file
      - traefik.http.services.pihole.loadbalancer.server.port=80

networks:
  traefik:
    external: true
    name: traefik

volumes:
  pihole_data:
    driver: nfs
    driver_opts:
      share: ${MASTER_IP}${CONFIGNFS}/misc/pihole/data
  pihole_dnsmasq:
    driver: nfs
    driver_opts:
      share: ${MASTER_IP}${CONFIGNFS}/misc/pihole/dnsmasq