version: "3.7"

services:
  #--------------------------#
  # Personal website
  #--------------------------#
  my-website:
    image: acouvreur/my-website
    environment:
      - TZ=${TZ}
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.my-website.rule=Host(`www.${DOMAINNAME}`)
        - traefik.http.routers.my-website.entrypoints=https
        - traefik.http.routers.my-website.middlewares=default-headers@file
        - traefik.http.routers.my-website.tls.domains[0].main=${DOMAINNAME}
        - traefik.http.routers.my-website.tls.domains[0].sans=*.${DOMAINNAME}
        - traefik.http.routers.my-website.tls.certresolver=ovh
        - traefik.http.services.my-website.loadbalancer.server.port=80

  #--------------------------#
  # Dynhost to update dynamic
  # IP to point to DOMAINNAME
  #--------------------------#
  dynhost:
    image: acouvreur/dynhost
    environment:
    - DYNHOST_DOMAIN_NAME
    - DYNHOST_LOGIN
    - DYNHOST_PASSWORD


  #---------------------------------------#
  # Open VPN Server
  #---------------------------------------#
  # openvpn-as:
  #   image: linuxserver/openvpn-as
  #   container_name: openvpn-as
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - TZ=${TZ}
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - INTERFACE=eth0 #optional
  #   volumes:
  #     - openvpn_config:/config
  #   ports:
  #     - 1194:1194/udp
  #   restart: unless-stopped
  #   networks:
  #     - traefik
  #   deploy:
  #     labels:
  #       - traefik.http.routers.vpn.rule=Host(`vpn.${DOMAINNAME}`)
  #       - traefik.http.services.vpn-service.loadbalancer.server.port=943
  #       - traefik.http.routers.vpn.middlewares=default-auth
  #       - "traefik.enable=true"

  # homeassistant:
  #   image: homeassistant/home-assistant:latest
  #   environment:
  #     - TZ=${TZ}
  #   networks:
  #     - traefik
  #   volumes:
  #     - homeassistant_data:/config
  #   deploy:
  #     labels:
  #       - traefik.enable=true
  #       - traefik.http.routers.home-assistant.rule=Host(`home-assistant.${DOMAINNAME}`)
  #       - traefik.http.routers.home-assistant.entrypoints=https
  #       - traefik.http.routers.home-assistant.tls.domains[0].main=${DOMAINNAME}
  #       - traefik.http.routers.home-assistant.tls.domains[0].sans=*.${DOMAINNAME}
  #       - traefik.http.routers.home-assistant.tls.certresolver=ovh
  #       - traefik.http.services.home-assistant.loadbalancer.server.port=8123

networks:
  traefik:
    external: true
    name: traefik

volumes:
  homeassistant_data:
    driver: nfs
    driver_opts:
      share: ${MASTER_IP}${CONFIGNFS}/misc/homeassistant/data
