version: "3.7"

services:

  #----------------------------------------------#
  # Pi-hole : dns wide blocking ads
  #----------------------------------------------#
  # pihole:
  #   hostname: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #     - '53:53/tcp'
  #     - '53:53/udp'
  #   volumes:
  #     - pihole_data:/etc/pihole
  #     - pihole_dnsmasq:/etc/dnsmasq.d
  #   networks:
  #     - traefik
  #   dns:
  #     - 127.0.0.1
  #     - 9.9.9.9
  #   environment:
  #     - VIRTUAL_HOST=pihole.${DOMAINNAME}
  #     - VIRTUAL_PORT=80
  #     - TZ=${TZ}
  #   deploy:
  #     labels:
  #       - traefik.enable=true
  #       - traefik.http.routers.pihole.rule=Host(`pihole.${DOMAINNAME}`)
  #       - traefik.http.routers.pihole.entrypoints=https
  #       - traefik.http.routers.pihole.tls.domains[0].main=${DOMAINNAME}
  #       - traefik.http.routers.pihole.tls.domains[0].sans=*.${DOMAINNAME}
  #       - traefik.http.routers.pihole.tls.certresolver=ovh
  #       - traefik.http.routers.pihole.middlewares=default-auth@file
  #       - traefik.http.services.pihole.loadbalancer.server.port=80


  #--------------------------#
  # Personal website
  #--------------------------#
  my-website:
    image: acouvreur/my-website
    environment:
      - TZ=${TZ}
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.my-website.rule=Host(`www.${DOMAINNAME}`)
        - traefik.http.routers.my-website.entrypoints=https
        - traefik.http.routers.my-website.middlewares=default-headers@file
        - traefik.http.routers.my-website.tls.domains[0].main=${DOMAINNAME}
        - traefik.http.routers.my-website.tls.domains[0].sans=*.${DOMAINNAME}
        - traefik.http.routers.my-website.tls.certresolver=ovh
        - traefik.http.services.my-website.loadbalancer.server.port=80

  #--------------------------#
  # Dynhost to update dynamic
  # IP to point to DOMAINNAME
  #--------------------------#
  dynhost:
    image: acouvreur/dynhost
    environment:
    - DYNHOST_DOMAIN_NAME
    - DYNHOST_LOGIN
    - DYNHOST_PASSWORD


  #---------------------------------------#
  # Open VPN Server
  #---------------------------------------#
  # openvpn-as:
  #   image: linuxserver/openvpn-as
  #   container_name: openvpn-as
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - TZ=${TZ}
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - INTERFACE=eth0 #optional
  #   volumes:
  #     - openvpn_config:/config
  #   ports:
  #     - 1194:1194/udp
  #   restart: unless-stopped
  #   networks:
  #     - traefik
  #   deploy:
  #     labels:
  #       - traefik.http.routers.vpn.rule=Host(`vpn.${DOMAINNAME}`)
  #       - traefik.http.services.vpn-service.loadbalancer.server.port=943
  #       - traefik.http.routers.vpn.middlewares=default-auth
  #       - "traefik.enable=true"

  homeassistant:
    image: homeassistant/home-assistant:latest
    environment:
      - TZ=${TZ}
    networks:
      - traefik
    volumes:
      - homeassistant_data:/config
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.home-assistant.rule=Host(`home-assistant.${DOMAINNAME}`)
        - traefik.http.routers.home-assistant.entrypoints=https
        - traefik.http.routers.home-assistant.tls.domains[0].main=${DOMAINNAME}
        - traefik.http.routers.home-assistant.tls.domains[0].sans=*.${DOMAINNAME}
        - traefik.http.routers.home-assistant.tls.certresolver=ovh
        - traefik.http.routers.home-assistant.middlewares=default-auth@file
        - traefik.http.services.home-assistant.loadbalancer.server.port=80

networks:
  traefik:
    external: true
    name: traefik

volumes:
  homeassistant_data:
    driver: nfs
    driver_opts:
      share: ${MASTER_IP}${CONFIGNFS}/misc/homeassistant/data
  pihole_data:
    driver: nfs
    driver_opts:
      share: ${MASTER_IP}${CONFIGNFS}/misc/pihole/data
  pihole_dnsmasq:
    driver: nfs
    driver_opts:
      share: ${MASTER_IP}${CONFIGNFS}/misc/pihole/dnsmasq
