#!/bin/bash

docker volume rm MEDIA_jackett_data MEDIA_movies MEDIA_radarr_config MEDIA_sonarr_config MEDIA_transmission_config MEDIA_transmission_data MEDIA_tvshows MONITORING_grafana_data MONITORING_influxdb_data
ssh Odin docker volume rm MEDIA_jackett_data MEDIA_movies MEDIA_radarr_config MEDIA_sonarr_config MEDIA_transmission_config MEDIA_transmission_data MEDIA_tvshows MONITORING_grafana_data MONITORING_influxdb_data
ssh Thor docker volume rm MEDIA_jackett_data MEDIA_movies MEDIA_radarr_config MEDIA_sonarr_config MEDIA_transmission_config MEDIA_transmission_data MEDIA_tvshows MONITORING_grafana_data MONITORING_influxdb_data
ssh Loki docker volume rm MEDIA_jackett_data MEDIA_movies MEDIA_radarr_config MEDIA_sonarr_config MEDIA_transmission_config MEDIA_transmission_data MEDIA_tvshows MONITORING_grafana_data MONITORING_influxdb_data
