version: "3.7"

services:

  #-------------------------------------#
  # Traefik : reverse proxy with HTTPS
  #-------------------------------------#
  traefik:
    hostname: traefik
    image: traefik:latest
    command:
      --certificatesresolvers.ovh.acme.dnschallenge=true
    networks:
      - traefik
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    environment:
      - OVH_ENDPOINT
      - OVH_APPLICATION_KEY
      - OVH_APPLICATION_SECRET
      - OVH_CONSUMER_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD:/etc/traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.entrypoints=https
        - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAINNAME}`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.middlewares=secured@file
        - traefik.http.routers.traefik.tls.domains[0].main=${DOMAINNAME}
        - traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAINNAME}
        - traefik.http.routers.traefik.tls.certresolver=ovh
        - traefik.http.services.traefik.loadbalancer.server.port=8080
      replicas: 1
      placement:
        constraints: [node.role==manager]
      update_config:
        order: stop-first

networks:
  traefik:
    external: true
    name: traefik
