
# Docker Swarm configuration
[providers.docker]
  # endpoint = "tcp://127.0.0.1:2377"
  endpoint = "unix:///var/run/docker.sock"
  swarmMode = true
  watch = true
  exposedbydefault = false
  network = "traefik"

[api]

# Entry Points
[entryPoints]
  # Default HTTP over :80
  [entryPoints.http]
  address = ":80"

  # HTTPS Entrypoint
  [entryPoints.https]
  address = ":443"

# Certificate resolver through HTTP Challenge
# OVH Providers needs these variables :
#   - OVH_ENDPOINT
#   - OVH_APPLICATION_KEY
#   - OVH_APPLICATION_SECRET
#   - OVH_CONSUMER_KEY
[certificatesResolvers.ovh.acme]
  dnsChallenge = true
  email = "alexiscouvreur.pro@gmail.com"
  storage = "/etc/traefik/acme/acme.json"
  [certificatesResolvers.ovh.acme.dnsChallenge]
    provider = "ovh"
    delayBeforeCheck = 0

[log]
  level = "INFO"
  format = "json"

[global]
  checkNewVersion = true

# Defines all middlewares to be used by services
[http.middlewares]
  [http.middlewares.default-auth.basicAuth]
    usersFile = "/etc/traefik/.htpasswd"
  [http.middlewares.redirect-to-https.redirectscheme]
    scheme = "https"

[http.routers]
  # HTTP to HTTPS redirection
  [http.routers.redirs]
    rule = "hostregexp(`{host:.+}`)"
    entrypoints = "http"
    middlewares = "redirect-to-https"

[metrics]
  [metrics.influxDB]
    address = "influxdb:8086"
    protocol = "http"
    database = "telegraf"
